mv ./api/createModelSchema.js ./api/createModelSchema.ts
mv ./api/createSimpleSchema.js ./api/createSimpleSchema.ts
mv ./api/getDefaultModelSchema.js ./api/getDefaultModelSchema.ts
mv ./api/serializable.js ./api/serializable.ts
mv ./api/setDefaultModelSchema.js ./api/setDefaultModelSchema.ts
mv ./constants.js ./constants.ts
mv ./core/cancelDeserialize.js ./core/cancelDeserialize.ts
mv ./core/Context.js ./core/Context.ts
mv ./core/deserialize.js ./core/deserialize.ts
mv ./core/serialize.js ./core/serialize.ts
mv ./core/serializeAll.js ./core/serializeAll.ts
mv ./core/update.js ./core/update.ts
mv ./serializr.js ./serializr.ts
mv ./types/alias.js ./types/alias.ts
mv ./types/custom.js ./types/custom.ts
mv ./types/date.js ./types/date.ts
mv ./types/identifier.js ./types/identifier.ts
mv ./types/list.js ./types/list.ts
mv ./types/map.js ./types/map.ts
mv ./types/mapAsArray.js ./types/mapAsArray.ts
mv ./types/object.js ./types/object.ts
mv ./types/optional.js ./types/optional.ts
mv ./types/primitive.js ./types/primitive.ts
mv ./types/raw.js ./types/raw.ts
mv ./types/reference.js ./types/reference.ts
mv ./utils/invariant.js ./utils/invariant.ts
mv ./utils/utils.js ./utils/utils.ts
